name:                BidirectionalSystem
version:             0.1.0.0
license:             BSD-3-Clause
author:              "Me"
copyright:           "2024 ME"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Test#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-top-binds
- -Wno-compat-unqualified-imports
- -Wno-unused-matches
- -Wno-name-shadowing
- -Wno-incomplete-uni-patterns
- -Wno-incomplete-patterns

library:
  source-dirs: src
  default-extensions:
  - LambdaCase
  - TypeFamilies
  - StandaloneDeriving
  - InstanceSigs
  - TupleSections

executables:
  BidirectionalSystem-exe:
    main:                Main.hs
    source-dirs:         .
    default-extensions: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BidirectionalSystem

tests:
  BidirectionalSystem-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BidirectionalSystem
